secret_key = "place secret key here"

[socket.control]
enabled = true
address = "control.sock"

[socket.event]
enabled = true
address = "event.sock"

[auth]
username = "broadcaster"

[segments]
directory = "stream/"
playlist = "stream.m3u8"
playlist_stale_threshold = 8.0
playlist_cache_lifetime = 0.2
search_cooldown = 0.25
search_timeout = 5.0
stream_initial_buffer = 3

[title]
file = "title.txt"
file_cache_lifetime = 0.5

[access]
captcha = true

[captcha]
lifetime = 1800
fonts = []
alphabet = "346abegkmprtuwxy"
length = 3
background_color = "#232327"
foreground_color = "#dddddd"

[memory]
states = 32
captchas = 256
failures = 256
chat_messages = 8192
chat_scrollback = 256

[tasks]
rotate_eyes = 3.0
rotate_users = 60.0
rotate_captchas = 60.0
rotate_websockets = 2.0
broadcast_ping = 8.0
broadcast_users_update = 4.0
broadcast_stream_info_update = 3.0

[names]
broadcaster = "Broadcaster"
anonymous = "Anonymous"

[chat]
max_comment_length = 512
max_comment_lines = 12
max_name_length = 24
min_name_contrast = 3.0
background_color = "#232327"
max_tripcode_password_length = 1024
legacy_tripcode_algorithm = false

[flood.messages]
duration = 20.0
threshold = 4

[flood.lines]
duration = 20.0
threshold = 20

[flood.video]
max_eyes = 3
cooldown = 12.0
expire_after = 5.0
overwrite = true

[presence]
notwatching = 8.0
tentative = 20.0
absent = 360.0

[nojs]
refresh_messages = 4.0
refresh_info = 6.0
refresh_users = 6.0
timeout_chat = 30.0
